# Generated by Django 5.0.2 on 2024-02-20 03:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('artist_name', models.CharField(max_length=30)),
                ('genre', models.CharField(choices=[('GENRE_POP_MUSIC', 'Pop Music'), ('GENRE_JAZ_MUSIC', 'Jazz Music'), ('GENRE_RNB_MUSIC', 'R&B Music'), ('GENRE_ROCK_MUSIC', 'Rock Music'), ('GENRE_COUNTRY_MUSIC', 'Country Music'), ('GENRE_DANCE_MUSIC', 'Dance Music'), ('GENRE_HIP_HO_MUSIC', 'Hip Hop Music'), ('GENRE_OTHER', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField()),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='profile.profile')),
            ],
        ),
    ]
